---
title: "Proj1-Lyrics"
author: "Tusha Ponkshe"
date: "9/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE,echo=FALSE}
packages.used=c("tm", "tidytext","tidyverse","DT","wordcloud","scales","gridExtra","ngram","igraph","ggraph","rsconnect")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

# load packages
library(tm)
library(tidytext)
library(tidyverse)
library(DT)
library(wordcloud)
library(scales)
library(gridExtra)
library(ngram)
library(igraph)
library(ggraph)
library(rsconnect)
```

```{r}
#loading processed lyrics data
load('../output/processed_lyrics.RData')
artists = read_csv('../data/artists.csv')
names(artists) = c("artist", "intro", "formed", "members", "origin")
leftJoinDf = dt_lyrics %>%
  left_join(artists, by = "artist")

leftJoinDf %>%
  group_by(genre, year) %>%
  tally()
ts.df = leftJoinDf %>%
  group_by(genre, year) %>%
  tally()

require(data.table)
new.ts.dt = data.table(ts.df)
final.ts.dt = new.ts.dt[ , .(Totalcount = sum(n)), by = .(year,genre)]

final.ts.df = data.frame(final.ts.dt)
#final.ts.df = final.ts.df[-c(79,80), ]

final.ts.df %>%
  filter(year > 2004, year < 2010)

final.ts.df %>%
  mutate(genre = fct_reorder(genre, Totalcount)) %>%
  filter(year > 1967, genre != "Other", genre != "Not Available") %>%
  ggplot(aes(x = year, y = Totalcount)) +
  geom_line(aes(color = genre), size = 1) +
  scale_x_continuous(breaks = seq(1965, 2020, 5))
```

